### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by jubalh** [sentriz/wlr-sunclock#1]
How about tagging a release? Then more Linux distros could add this.

**Comment by sentriz** [comment]
good idea. thanks!
added a script to automate it
https://github.com/sentriz/wlr-sunclock/blob/master/release

not sure if that's standard practise but seems to be ok

**Comment by sentriz** [comment]
if you know of a better way to do releases in a c / meson project i'd love to hear it :)

**Comment by jubalh** [comment]
Thanks!
