### ISSUE TITLE
-X linker option breaks aarch64 build

### ISSUE THREAD

**Issue by bhepple** [sentriz/wlr-sunclock#6]
I'm trying to push through a Fedora package and we normally build on a variety of platforms but the -X linker option (--discard-locals) is breaking on aarch64:

gcc  -o wlr-sunclock wlr-sunclock.p/src_main.c.o wlr-sunclock.p/src_gui.c.o wlr-sunclock.p/src_astro.c.o -Wl,--as-needed -Wl,--no-undefined -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -mbranch-protection=standard -fasynchronous-unwind-tables -fstack-clash-protection -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -X -Wl,--start-group -lm /usr/lib64/libgtk-3.so /usr/lib64/libgdk-3.so /usr/lib64/libpangocairo-1.0.so /usr/lib64/libpango-1.0.so /usr/lib64/libharfbuzz.so /usr/lib64/libatk-1.0.so /usr/lib64/libcairo-gobject.so /usr/lib64/libcairo.so /usr/lib64/libgdk_pixbuf-2.0.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-2.0.so /usr/lib64/libgtk-layer-shell.so -Wl,--end-group
gcc: error: unrecognized command-line option ‘-X’
ninja: build stopped: subcommand failed.

Is it essential, would it be appropriate to remove the -X option globally or do you think that would it harm the other platforms?

I realise this may be a bug in the toolchain - perhaps it's just that gcc is not passing -X to the linker??

Another alternative would be to not build on aarch64.

**Comment by sentriz** [comment]
hmm strange - I don't even know why -X is there. seems to be working without it 

removed it now. do you need a new release to test the changes? thanks!

**Comment by bhepple** [comment]
Thanks for that!

I can do a patch for this release so no need for another just yet.

**Comment by sentriz** [comment]
🙏
