### ISSUE TITLE
Map color palette

### ISSUE THREAD

**Issue by julien-tdx** [sentriz/wlr-sunclock#7]
Hi, it would be nice to choose other colors for the map background

**Comment by sentriz** [comment]
cool suggestions thanks!

to do this I made the map an svg to it can be changed easily (librsvg 2 is required now  @bhepple  @jubalh  🙏)

so now you could try something like `-o "#ECFDF5" -n "#831843"`

I will make a new release soon

**Comment by julien-tdx** [comment]
Thanks, it's better with the colors !
I've got quite a few feature requests ideas, I'll create dedicated issues
